version: "3.8"

services:
  name:
    image: strm/dnsmasq
    container_name: dnsmasq
    restart: always
    ports:
      - "53:53/udp"
#      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:Z
    command: [ "--no-daemon", "--log-queries", "--log-dhcp" ]
