version: '3.8'
services:
  dnsmasq:
    image: strm/dnsmasq
    container_name: dnsmasq
    ports:
      - "53:53/udp"
#      - "53:53/tcp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:Z
    command: ["--no-daemon", "--log-queries", "--log-dhcp"]
    restart: unless-stopped