version: "3"

volumes:
  nexus-data: {}

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_https.conf:/etc/nginx/nginx.conf
      - /root/certs:/etc/certs
      #- ./default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8085:8085"
