data "openstack_images_image_v2" "ubuntu" {
  name = "ubuntu-20.04-server-cloudimg-amd64.img"
}

resource "openstack_compute_aggregate_v2" "aggr_1" {
  name = "aggr_1"
  hosts = [
    "ebochkov-keystack-comp-01",
    "ebochkov-keystack-comp-02",
  ]
  zone = "az_1"
}

resource "openstack_compute_aggregate_v2" "aggr_2" {
  name = "aggr_2"
  hosts = [
    "ebochkov-keystack-comp-03",
    "ebochkov-keystack-comp-04",
  ]
  zone = "az_2"
}

resource "openstack_compute_flavor_v2" "vm_1_flavor" {
  name      = "terraform_flavor"
  vcpus     = 2
  ram       = 2048
  disk      = 0
}

resource "openstack_compute_keypair_v2" "kp_1" {
  name = "terraform_keypair"
}

output "id_rsa_private_key" {
  value       = openstack_compute_keypair_v2.kp_1.private_key
  sensitive   = true
  description = "Generated private SSH key (id_rsa equivalent)"
}

output "id_rsa_public_key" {
  value       = openstack_compute_keypair_v2.kp_1.public_key
  description = "Generated public SSH key"
}

output "ssh_keypair_info" {
  value = {
    name        = openstack_compute_keypair_v2.kp_1.name
    fingerprint = openstack_compute_keypair_v2.kp_1.fingerprint
    key_type    = "RSA (generated by Terraform)"
  }
  description = "SSH keypair information"
}

resource "openstack_blockstorage_volume_v3" "boot_volumes" {
  count = 4
  name  = "boot-volume-vm-1-${count.index + 1}"
  size  = 5
  image_id = data.openstack_images_image_v2.ubuntu.id
}

resource "openstack_blockstorage_volume_v3" "data_volumes_1" {
  count = 4
  name  = "data-volume-1-vm-1-${count.index + 1}"
  size  = 1
}

resource "openstack_blockstorage_volume_v3" "data_volumes_2" {
  count = 4
  name  = "data-volume-2-vm-1-${count.index + 1}"
  size  = 2
}

resource "openstack_compute_instance_v2" "vm" {
  count                         = 4
  name                          = "vm_1-${count.index + 1}"
  key_pair                      = openstack_compute_keypair_v2.kp_1.name
  flavor_id                     = openstack_compute_flavor_v2.vm_1_flavor.id
  availability_zone_hints       = "az_2:ebochkov-keystack-comp-03"

  network {
    name = "pub_net"
  }

  block_device {
    uuid                  = openstack_blockstorage_volume_v3.boot_volumes[count.index].id
    source_type           = "volume"
    destination_type      = "volume"
    boot_index            = 0
    delete_on_termination = false
  }

  depends_on = [
    openstack_compute_aggregate_v2.aggr_1,
    openstack_compute_aggregate_v2.aggr_2
  ]
}

resource "openstack_compute_volume_attach_v2" "attach_data_1" {
  count       = 4
  instance_id = openstack_compute_instance_v2.vm[count.index].id
  volume_id   = openstack_blockstorage_volume_v3.data_volumes_1[count.index].id
}

resource "openstack_compute_volume_attach_v2" "attach_data_2" {
  count       = 4
  instance_id = openstack_compute_instance_v2.vm[count.index].id
  volume_id   = openstack_blockstorage_volume_v3.data_volumes_2[count.index].id
}