# config/config.yml
# Services list for diagnostics

# logging
log:
  enable_log: True                  # False by default
#  path: "/var/log/openstack-pulse"  # /tmp by default

# Check services
check_services:
  - nova
  - cinder
  - neutron
  - keystone
  - rabbitmq
  - galera

# Single check services
single_mode_checks:
  - placement

# Timing parameters
intervals:
  check_interval: 5           # Interval between checks (seconds)
  collection_window: 300      # Data collection window (seconds) - 5 minutes

# Endpoints
endpoints:
  rabbitmq_port: 15672
  mariadb_port: 3306

# Pulse settings
heartbeat_requests_services: 4