# config/config.yml
# Services list for diagnostics

# logging
log:
  enable_log: True
#  path: "/var/log/openstack-pulse"  # /tmp by default

# Check services
check_services:
  - nova
  - cinder
  - neutron
  - keystone
  - rabbitmq
  - galera
  - adminui

# Single check services
single_mode_checks:
  - placement

# Endpoints
endpoints:
  mariadb_port: 3306

adminui:
  protocol: "https"
  port: 12999
#  cacert_path: "/path/to/ca-bundle.crt"

rabbitmq:
#  username: "" from ENV RABBIT_USER
#  password: "" from ENV RABBIT_PASS

  protocol: "https"
  port: "15672"

# Timing parameters
intervals:
  check_interval: 5   # Interval between checks (seconds)
  duration: 300       # Data collection window (seconds) - 5 minutes

# Pulse settings
heartbeat_requests_services: 4