---
- name: Check Ansible configuration variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show actual Ansible configuration vars
      debug:
        msg: |
          forks: {{ ansible_connection }}
          timeout: {{ ansible_timeout }}
          become: {{ ansible_become }}
          become_method: {{ ansible_become_method }}
          become_user: {{ ansible_become_user }}
#  hosts: control[0]
