---
- name: Check Ansible configuration variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show Ansible configuration variables
      debug:
        msg: |
          ansible_forks: {{ ansible_forks }}
          ansible_timeout: {{ ansible_timeout }}
          ansible_gather_facts: {{ ansible_gather_facts }}
          ansible_host_key_checking: {{ ansible_host_key_checking }}
          ansible_become: {{ ansible_become }}
          ansible_become_method: {{ ansible_become_method }}
#  hosts: control[0]
