# ansible/playbooks/check_containers.yml
---
- name: Check Podman containers
  hosts: control[0]
  gather_facts: false
  tasks:
    - name: List running containers
      command: podman ps --format "table {{.Names}}\t{{.Status}}\t{{.RunningFor}}"
      register: containers_json
    - name: Show container list
      debug:
        var: containers_json.stdout
