---
- name: Test Ansible configuration
  hosts: control[0]
  tasks:
    - name: Get Ansible configuration
      shell: ansible-config dump --only-changed
      register: ansible_config

    - name: Show configuration
      debug:
        var: ansible_config.stdout