version: '3.8'
services:
  dns:
    restart: unless-stopped
    container_name: dnsmasq
    image: strm/dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:Z,ro  # :Z для SELinux, ro для безопасности
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    user: "root:root"