#cloud-config
chpasswd:
  expire: false
  users:
    - name: ubuntu
      password: "$6$1RIJCwfWrd3WqaPd$sKcB5WNabsMQmCl3mu1JwJUsyrgNJdux5Ahj/6e1o79RRIyDwCjjEh44lqbo18T3lmOxfHuzlXpTwfvebO7S61"
      type: hash
ssh_pwauth: true

write_files:
  - path: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      DNS=8.8.8.8 8.8.4.4 77.88.8.8
      FallbackDNS=1.1.1.1
      Domains=~.

  - path: /tmp/nuttcp_logger.sh
    content: |
      #!/bin/bash

      # Example usage: bash ./nuttcp_logger.sh 10.224.54.80 -u -i1 -T10 -R 25m -f-drops
      
      default_log_file="nuttcp_$(date '+%Y-%m-%d').log"
      [[ -z $LOG_FILE ]] && LOG_FILE=$default_log_file
      
      # Validate IP address format
      function validate_ip() {
        grep -E -q '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$' <<< "$1"
      }
      
      # Check for server IP argument
      if [ -z "$1" ]; then
          echo "Error: Server IP not specified" >&2
          echo "Usage: $0 <server_ip> [additional_nuttcp_parameters]" >&2
          exit 1
      fi
      
      SERVER="$1"
      
      # Validate IP format
      if ! validate_ip "$SERVER"; then
          echo "Error: Invalid IP address format" >&2
          exit 1
      fi
      
      shift  # Remove first argument (IP), pass remaining to nuttcp
      
      # Write test header
      echo "===== Test started at $(date) - Server: $SERVER =====" >> "$LOG_FILE"
      
      # Run nuttcp with parameters and log output
      nuttcp "$@" "$SERVER" | while read -r line; do
          echo "$(date '+%H:%M:%S') $line" >> "$LOG_FILE"
      done
      
      # Write test footer
      echo "===== Test completed at $(date) - Server: $SERVER =====" >> "$LOG_FILE"
    permissions: '0755'

runcmd:
  - echo "Custom cloud-init commands started executing..." >> /var/log/cloud-init-output.log
  - systemctl restart systemd-resolved
  - |
    for i in {1..6}; do
      apt-get update && apt-get install -y iperf3 nuttcp && break || sleep 10
    done
  - cp /tmp/nuttcp_logger.sh /home/ubuntu/
  - chown ubuntu:ubuntu /home/ubuntu/nuttcp_logger.sh
  - echo "Custom cloud initialization commands completed!" >> /var/log/cloud-init-output.log
