#cloud-config
chpasswd:
  expire: false
  users:
    - name: ubuntu
      password: "$6$1RIJCwfWrd3WqaPd$sKcB5WNabsMQmCl3mu1JwJUsyrgNJdux5Ahj/6e1o79RRIyDwCjjEh44lqbo18T3lmOxfHuzlXpTwfvebO7S61"
      type: hash
ssh_pwauth: true

write_files:
  - path: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      DNS=8.8.8.8 8.8.4.4 77.88.8.8
      FallbackDNS=1.1.1.1
      Domains=~.

runcmd:
  - echo "Custom cloud-init commands started executing..." >> /var/log/cloud-init-output.log
  - systemctl restart systemd-resolved
  - |
    for i in {1..6}; do
      apt-get update && apt-get install -y iperf3 && break || sleep 10
    done
