#cloud-config
chpasswd:
  expire: false
  users:
    - name: ubuntu
      password: "$6$1RIJCwfWrd3WqaPd$sKcB5WNabsMQmCl3mu1JwJUsyrgNJdux5Ahj/6e1o79RRIyDwCjjEh44lqbo18T3lmOxfHuzlXpTwfvebO7S61"
      type: hash
ssh_pwauth: true

write_files:
  - path: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      DNS=8.8.8.8 8.8.4.4 77.88.8.8
      FallbackDNS=1.1.1.1
      Domains=~.
  - path: /home/ubuntu/iperf_loop.sh
    content: |
      #!/bin/bash
      
      # To start
      #   nohup ./iperf_loop.sh 10.224.54.58:5201 >/dev/null 2>&1 &
      # To check
      #   ss -ntp
      #   tail -f /tmp/iperf_client.log
      # To stop
      #   kill $(cat /tmp/iperf_client.pid)
      
      # Configuration
      LOG_FILE="/tmp/iperf_client_$$.log"  # Unique log file per process
      PID_FILE="/tmp/iperf_client.pid"
      DEFAULT_PORT="5201"
      MAX_RETRIES=3
      RETRY_DELAY=5
      
      # Enhanced logging
      log() {
          echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
      }
      
      # Simplified input parsing
      parse_input() {
          IFS=":" read -r SERVER_IP SERVER_PORT <<< "$1"
          SERVER_PORT=${SERVER_PORT:-$DEFAULT_PORT}
      }
      
      # Connection test with retries
      check_connection() {
          local ip=$1 port=$2 retry=0
          
          for ((retry=0; retry<MAX_RETRIES; retry++)); do
              if timeout 2 bash -c "cat < /dev/null > /dev/tcp/$ip/$port" 2>/dev/null; then
                  return 0
              fi
              log "Connection attempt $((retry+1))/$MAX_RETRIES failed"
              sleep $RETRY_DELAY
          done
          
          log "ERROR: Cannot connect to $ip:$port after $MAX_RETRIES attempts"
          return 1
      }
      
      # Main function with proper cleanup
      run_test() {
          # Create PID file
          echo $$ > "$PID_FILE"
          trap "rm -f '$PID_FILE'" EXIT
          
          # Parse input
          local server_input="${1:-$IPERF_SERVER}"
          [ -z "$server_input" ] && { log "ERROR: No server specified"; exit 1; }
          
          parse_input "$server_input"
          log "Starting test for $SERVER_IP:$SERVER_PORT (PID: $$)"
          
          # Verify connection
          check_connection "$SERVER_IP" "$SERVER_PORT" || exit 1
          
          # Main test loop
          while true; do
              log "Running iperf test..."
              iperf3 -c "$SERVER_IP" -p "$SERVER_PORT" -t 1 --connect-timeout 5000 >> "$LOG_FILE" 2>&1
              sleep 1
          done
      }
      
      # Execution guard
      if [ "$1" = "--daemon" ]; then
          run_test "${@:2}"
      else
          nohup "$0" --daemon "$@" >> "$LOG_FILE" 2>&1 &
          echo "Daemon started (PID: $!)"
          echo "Log file: $LOG_FILE"
          echo "Control: kill \$(cat $PID_FILE 2>/dev/null)"
      fi
    permissions: '0755'

runcmd:
  - echo "Custom cloud-init commands started executing..." >> /var/log/cloud-init-output.log
  - systemctl restart systemd-resolved
  - |
    for i in {1..6}; do
      apt-get update && apt-get install -y iperf3 && break || sleep 10
    done
  - cp /tmp/iperf_loop.sh /home/ubuntu/iperf_loop.sh
  - chown ubuntu:ubuntu /home/ubuntu/iperf_loop.sh
  - echo "Custom cloud initialization commands completed!" >> /var/log/cloud-init-output.log
