paths:
  reports_dir: "./reports"        # отчёты в директории проекта
  log_dir: "/tmp"                 # логи в системном /tmp
  #  ansible_dir: "./ansible"
  #  inventory: "./inventory.ini"
  #  ansible_cfg: "./ansible/ansible.cfg"
  #  playbooks_dir: "./ansible/playbooks

logging:
  level: "INFO"           # общий уровень
  console_output: true    # вывод в консоль
  file_output: true       # вывод в файл
  color_output: true      # цветной вывод

nodes:
  controllers: ["controller01"]
  computes: ["compute01", "compute02"]

services:
  containers: {enabled: true, timeout: 60}
  keystone: {enabled: true, timeout: 30}
  # ...

thresholds:
  container_restarts: 10
  # ...

#ansible:
#
#
#
#  forks: 20
#  gather_facts: false
#  strategy: free
#  timeout: 30
#  ssh_args: "-o ControlMaster=auto -o ControlPersist=300s"
#  display_skipped_hosts: false